### ISSUE TITLE
JUSMIMS TOTALLY cheats

### ISSUE THREAD

**Issue by Awul** [JuSmims/ESP_IR_WEB#7]
JUSMIMS does commits, like completely reuploading or completely restructuring the project to increase his edit count.ml !!!!

**Comment by JuSmims** [comment]
I dont think that you can cheat in this game. I am simply preferred by the .ml commitee.ml!

**Comment by Awul** [comment]
Even if its closed, it isn´t closed in our hearts.

**Comment by Awul** [comment]
Deleting is just "censoring" yourself.

**Comment by Awul** [comment]
Its still relevant.
